"""Núcleo do controle de acesso baseado em papéis (RBAC).

Define:
    * O catálogo de permissões do sistema (fonte única de verdade), no formato
      ``modulo.recurso.acao``.
    * O catálogo de papéis-modelo (templates) semeados por tenant.
    * A lógica pura de verificação de permissões (com suporte a curingas).

A resolução das permissões efetivas de um usuário (a partir de seus papéis) é
responsabilidade do módulo *identity*; aqui ficam apenas as regras puras.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class PermissionDef:
    """Definição de uma permissão do sistema."""

    code: str
    module: str
    resource: str
    action: str
    description: str


@dataclass(frozen=True, slots=True)
class RoleTemplate:
    """Definição de um papel-modelo semeado em cada tenant."""

    slug: str
    name: str
    description: str
    is_system: bool = True
    # Lista de códigos de permissão; "*" concede todas.
    permissions: tuple[str, ...] = field(default_factory=tuple)


def _perm(module: str, resource: str, action: str, description: str) -> PermissionDef:
    return PermissionDef(
        code=f"{module}.{resource}.{action}",
        module=module,
        resource=resource,
        action=action,
        description=description,
    )


# ==========================================================================
# CATÁLOGO DE PERMISSÕES DO SISTEMA (Fase 0 - fundação + administração)
# Módulos de negócio adicionarão suas permissões nas próximas fases.
# ==========================================================================
SYSTEM_PERMISSIONS: tuple[PermissionDef, ...] = (
    # ---- Dashboard ----
    _perm("dashboard", "painel", "visualizar", "Visualizar dashboards e KPIs"),
    # ---- Identidade: usuários ----
    _perm("identidade", "usuario", "visualizar", "Visualizar usuários"),
    _perm("identidade", "usuario", "criar", "Criar usuários"),
    _perm("identidade", "usuario", "editar", "Editar usuários"),
    _perm("identidade", "usuario", "excluir", "Excluir usuários"),
    # ---- Identidade: papéis/permissões ----
    _perm("identidade", "papel", "visualizar", "Visualizar papéis e permissões"),
    _perm("identidade", "papel", "criar", "Criar papéis"),
    _perm("identidade", "papel", "editar", "Editar papéis e vincular permissões"),
    _perm("identidade", "papel", "excluir", "Excluir papéis"),
    # ---- Empresa (tenant) ----
    _perm("configuracoes", "empresa", "visualizar", "Visualizar dados da empresa"),
    _perm("configuracoes", "empresa", "editar", "Editar dados da empresa"),
    # ---- Filiais ----
    _perm("configuracoes", "filial", "visualizar", "Visualizar filiais/unidades"),
    _perm("configuracoes", "filial", "criar", "Criar filiais/unidades"),
    _perm("configuracoes", "filial", "editar", "Editar filiais/unidades"),
    _perm("configuracoes", "filial", "excluir", "Excluir filiais/unidades"),
    _perm("configuracoes", "parametro", "visualizar", "Visualizar parâmetros do sistema"),
    _perm("configuracoes", "parametro", "editar", "Editar parâmetros do sistema"),
    # ---- Cadastros ----
    _perm("cadastros", "cliente", "visualizar", "Visualizar clientes"),
    _perm("cadastros", "cliente", "criar", "Criar clientes"),
    _perm("cadastros", "cliente", "editar", "Editar clientes"),
    _perm("cadastros", "cliente", "excluir", "Excluir clientes"),
    _perm("cadastros", "cliente", "bloquear", "Bloquear clientes / blacklist"),
    _perm("cadastros", "tabela", "visualizar", "Visualizar tabelas auxiliares"),
    _perm("cadastros", "tabela", "criar", "Criar itens de tabelas auxiliares"),
    _perm("cadastros", "tabela", "editar", "Editar tabelas auxiliares"),
    _perm("cadastros", "tabela", "excluir", "Excluir tabelas auxiliares"),
    _perm("cadastros", "motorista", "visualizar", "Visualizar motoristas"),
    _perm("cadastros", "motorista", "criar", "Criar motoristas"),
    _perm("cadastros", "motorista", "editar", "Editar motoristas"),
    _perm("cadastros", "motorista", "excluir", "Excluir motoristas"),
    _perm("cadastros", "parceiro", "visualizar", "Visualizar parceiros"),
    _perm("cadastros", "parceiro", "criar", "Criar parceiros"),
    _perm("cadastros", "parceiro", "editar", "Editar parceiros"),
    _perm("cadastros", "parceiro", "excluir", "Excluir parceiros"),
    _perm("cadastros", "fornecedor", "visualizar", "Visualizar fornecedores"),
    _perm("cadastros", "fornecedor", "criar", "Criar fornecedores"),
    _perm("cadastros", "fornecedor", "editar", "Editar fornecedores"),
    _perm("cadastros", "fornecedor", "excluir", "Excluir fornecedores"),
    _perm("cadastros", "vendedor", "visualizar", "Visualizar vendedores"),
    _perm("cadastros", "vendedor", "criar", "Criar vendedores"),
    _perm("cadastros", "vendedor", "editar", "Editar vendedores"),
    _perm("cadastros", "vendedor", "excluir", "Excluir vendedores"),
    # ---- Frota ----
    _perm("frota", "veiculo", "visualizar", "Visualizar veículos"),
    _perm("frota", "veiculo", "criar", "Criar veículos"),
    _perm("frota", "veiculo", "editar", "Editar veículos"),
    _perm("frota", "veiculo", "excluir", "Excluir veículos"),
    _perm("frota", "veiculo", "bloquear", "Bloquear veículos"),
    _perm("frota", "veiculo", "baixar", "Baixar veículos (venda/sinistro)"),
    _perm("frota", "categoria", "visualizar", "Visualizar categorias de frota"),
    _perm("frota", "categoria", "criar", "Criar categorias de frota"),
    _perm("frota", "categoria", "editar", "Editar categorias de frota"),
    _perm("frota", "categoria", "excluir", "Excluir categorias de frota"),
    _perm("frota", "marca", "visualizar", "Visualizar marcas"),
    _perm("frota", "marca", "criar", "Criar marcas"),
    _perm("frota", "marca", "editar", "Editar marcas"),
    _perm("frota", "marca", "excluir", "Excluir marcas"),
    _perm("frota", "modelo", "visualizar", "Visualizar modelos"),
    _perm("frota", "modelo", "criar", "Criar modelos"),
    _perm("frota", "modelo", "editar", "Editar modelos"),
    _perm("frota", "modelo", "excluir", "Excluir modelos"),
    _perm("frota", "combustivel", "visualizar", "Visualizar combustíveis"),
    _perm("frota", "combustivel", "criar", "Criar combustíveis"),
    _perm("frota", "combustivel", "editar", "Editar combustíveis"),
    _perm("frota", "combustivel", "excluir", "Excluir combustíveis"),
    _perm("frota", "acessorio", "visualizar", "Visualizar acessórios"),
    _perm("frota", "acessorio", "criar", "Criar acessórios"),
    _perm("frota", "acessorio", "editar", "Editar acessórios"),
    _perm("frota", "acessorio", "excluir", "Excluir acessórios"),
    _perm("frota", "documentacao", "visualizar", "Visualizar documentação de veículos"),
    _perm("frota", "documentacao", "criar", "Criar documentação de veículos"),
    _perm("frota", "documentacao", "editar", "Editar documentação de veículos"),
    _perm("frota", "documentacao", "excluir", "Excluir documentação de veículos"),
    _perm("frota", "telemetria", "visualizar", "Visualizar telemetria"),
    _perm("frota", "telemetria", "criar", "Cadastrar dispositivos de telemetria"),
    _perm("frota", "telemetria", "editar", "Editar telemetria / registrar eventos"),
    _perm("frota", "telemetria", "excluir", "Excluir dispositivos de telemetria"),
    # ---- Manutenção ----
    _perm("manutencao", "os", "visualizar", "Visualizar ordens de serviço"),
    _perm("manutencao", "os", "criar", "Criar ordens de serviço"),
    _perm("manutencao", "os", "editar", "Editar ordens de serviço"),
    _perm("manutencao", "os", "excluir", "Excluir/cancelar ordens de serviço"),
    _perm("manutencao", "os", "aprovar", "Aprovar ordens de serviço acima do limite"),
    _perm("manutencao", "preventiva", "visualizar", "Visualizar planos preventivos"),
    _perm("manutencao", "preventiva", "criar", "Criar planos preventivos"),
    _perm("manutencao", "preventiva", "editar", "Editar planos preventivos"),
    _perm("manutencao", "preventiva", "excluir", "Excluir planos preventivos"),
    _perm("manutencao", "corretiva", "visualizar", "Visualizar OS corretivas"),
    _perm("manutencao", "corretiva", "criar", "Criar OS corretivas"),
    _perm("manutencao", "corretiva", "editar", "Editar OS corretivas"),
    _perm("manutencao", "peca", "visualizar", "Visualizar peças e estoque"),
    _perm("manutencao", "peca", "criar", "Criar peças / entradas de estoque"),
    _perm("manutencao", "peca", "editar", "Editar peças e movimentar estoque"),
    _perm("manutencao", "peca", "excluir", "Excluir peças"),
    _perm("manutencao", "pneu", "visualizar", "Visualizar pneus"),
    _perm("manutencao", "pneu", "criar", "Criar pneus"),
    _perm("manutencao", "pneu", "editar", "Editar / instalar / rodízio de pneus"),
    _perm("manutencao", "pneu", "excluir", "Excluir pneus"),
    # ---- Tarifário ----
    _perm("tarifario", "tabela", "visualizar", "Visualizar tabelas de tarifas"),
    _perm("tarifario", "tabela", "criar", "Criar tabelas de tarifas"),
    _perm("tarifario", "tabela", "editar", "Editar tabelas de tarifas"),
    _perm("tarifario", "tabela", "excluir", "Excluir tabelas de tarifas"),
    _perm("tarifario", "temporada", "visualizar", "Visualizar temporadas"),
    _perm("tarifario", "temporada", "criar", "Criar temporadas"),
    _perm("tarifario", "temporada", "editar", "Editar temporadas"),
    _perm("tarifario", "temporada", "excluir", "Excluir temporadas"),
    _perm("tarifario", "taxa", "visualizar", "Visualizar taxas e encargos"),
    _perm("tarifario", "taxa", "criar", "Criar taxas e encargos"),
    _perm("tarifario", "taxa", "editar", "Editar taxas e encargos"),
    _perm("tarifario", "taxa", "excluir", "Excluir taxas e encargos"),
    _perm("tarifario", "protecao", "visualizar", "Visualizar proteções"),
    _perm("tarifario", "protecao", "criar", "Criar proteções"),
    _perm("tarifario", "protecao", "editar", "Editar proteções"),
    _perm("tarifario", "protecao", "excluir", "Excluir proteções"),
    _perm("tarifario", "politica", "visualizar", "Visualizar políticas de cancelamento"),
    _perm("tarifario", "politica", "criar", "Criar políticas de cancelamento"),
    _perm("tarifario", "politica", "editar", "Editar políticas de cancelamento"),
    _perm("tarifario", "politica", "excluir", "Excluir políticas de cancelamento"),
    _perm("tarifario", "simular", "visualizar", "Simular preços (PricingService)"),
    # ---- Reservas ----
    _perm("reservas", "reserva", "visualizar", "Visualizar reservas"),
    _perm("reservas", "reserva", "criar", "Criar reservas"),
    _perm("reservas", "reserva", "editar", "Editar reservas"),
    _perm("reservas", "reserva", "cancelar", "Cancelar reservas"),
    _perm("reservas", "reserva", "aprovar", "Aprovar reserva de cliente bloqueado"),
    _perm("reservas", "calendario", "visualizar", "Visualizar calendário de reservas"),
    _perm("reservas", "disponibilidade", "visualizar", "Consultar disponibilidade"),
    _perm("reservas", "cotacao", "visualizar", "Visualizar cotações"),
    _perm("reservas", "cotacao", "criar", "Criar cotações"),
    _perm("reservas", "cotacao", "editar", "Editar cotações"),
    _perm("reservas", "cotacao", "excluir", "Excluir cotações"),
    # ---- Locações ----
    _perm("locacoes", "contrato", "visualizar", "Visualizar contratos"),
    _perm("locacoes", "contrato", "criar", "Criar contratos"),
    _perm("locacoes", "contrato", "editar", "Editar contratos"),
    _perm("locacoes", "contrato", "cancelar", "Cancelar contratos"),
    _perm("locacoes", "checkout", "visualizar", "Visualizar check-out"),
    _perm("locacoes", "checkout", "criar", "Iniciar check-out"),
    _perm("locacoes", "checkout", "editar", "Concluir check-out"),
    _perm("locacoes", "checkin", "visualizar", "Visualizar check-in"),
    _perm("locacoes", "checkin", "criar", "Iniciar check-in"),
    _perm("locacoes", "checkin", "editar", "Concluir check-in"),
    _perm("locacoes", "renovacao", "visualizar", "Visualizar renovações"),
    _perm("locacoes", "renovacao", "criar", "Renovar contratos"),
    _perm("locacoes", "encerramento", "visualizar", "Visualizar encerramentos"),
    _perm("locacoes", "encerramento", "reabrir", "Reabrir contratos encerrados"),
    _perm("locacoes", "multa", "visualizar", "Visualizar multas"),
    _perm("locacoes", "multa", "criar", "Registrar multas"),
    _perm("locacoes", "multa", "editar", "Editar multas"),
    _perm("locacoes", "multa", "excluir", "Excluir multas"),
    _perm("locacoes", "avaria", "visualizar", "Visualizar avarias"),
    _perm("locacoes", "avaria", "criar", "Registrar avarias"),
    _perm("locacoes", "avaria", "editar", "Editar avarias"),
    # ---- Financeiro (§9) ----
    _perm("financeiro", "caixa", "visualizar", "Visualizar caixa"),
    _perm("financeiro", "caixa", "criar", "Criar lançamentos de caixa"),
    _perm("financeiro", "caixa", "editar", "Editar lançamentos de caixa"),
    _perm("financeiro", "caixa", "abrir", "Abrir sessão de caixa"),
    _perm("financeiro", "caixa", "fechar", "Fechar sessão de caixa"),
    _perm("financeiro", "receber", "visualizar", "Visualizar contas a receber"),
    _perm("financeiro", "receber", "criar", "Criar títulos a receber"),
    _perm("financeiro", "receber", "editar", "Editar/cancelar títulos a receber"),
    _perm("financeiro", "receber", "baixar", "Baixar títulos a receber"),
    _perm("financeiro", "receber", "estornar", "Estornar títulos a receber"),
    _perm("financeiro", "pagar", "visualizar", "Visualizar contas a pagar"),
    _perm("financeiro", "pagar", "criar", "Criar títulos a pagar"),
    _perm("financeiro", "pagar", "editar", "Editar/cancelar títulos a pagar"),
    _perm("financeiro", "pagar", "aprovar", "Aprovar títulos a pagar"),
    _perm("financeiro", "pagar", "efetivar", "Efetivar pagamentos"),
    _perm("financeiro", "pix", "visualizar", "Visualizar PIX"),
    _perm("financeiro", "pix", "criar", "Criar chaves/cobranças PIX"),
    _perm("financeiro", "pix", "editar", "Editar/confirmar cobranças PIX"),
    _perm("financeiro", "cartoes", "visualizar", "Visualizar transações de cartão"),
    _perm("financeiro", "cartoes", "criar", "Autorizar transações de cartão"),
    _perm("financeiro", "cartoes", "editar", "Capturar/estornar transações de cartão"),
    _perm("financeiro", "bancos", "visualizar", "Visualizar contas bancárias"),
    _perm("financeiro", "bancos", "criar", "Criar contas bancárias"),
    _perm("financeiro", "bancos", "editar", "Editar contas bancárias"),
    _perm("financeiro", "conciliacao", "visualizar", "Visualizar conciliação bancária"),
    _perm("financeiro", "conciliacao", "criar", "Importar extratos para conciliação"),
    _perm("financeiro", "conciliacao", "editar", "Conciliar linhas de extrato"),
    _perm("financeiro", "faturamento", "visualizar", "Visualizar faturamento"),
    _perm("financeiro", "faturamento", "criar", "Consolidar faturas / configurar ciclos"),
    _perm("financeiro", "faturamento", "editar", "Emitir faturas"),
    # ---- Comercial / CRM (§7) ----
    _perm("comercial", "funil", "visualizar", "Visualizar funil de vendas"),
    _perm("comercial", "funil", "criar", "Criar oportunidades/interações no funil"),
    _perm("comercial", "funil", "editar", "Mover estágio / editar oportunidades"),
    _perm("comercial", "proposta", "visualizar", "Visualizar propostas"),
    _perm("comercial", "proposta", "criar", "Criar propostas"),
    _perm("comercial", "proposta", "editar", "Editar / enviar / aceitar propostas"),
    _perm("comercial", "proposta", "excluir", "Excluir propostas"),
    _perm("comercial", "campanha", "visualizar", "Visualizar campanhas"),
    _perm("comercial", "campanha", "criar", "Criar campanhas"),
    _perm("comercial", "campanha", "editar", "Editar / disparar campanhas"),
    _perm("comercial", "campanha", "excluir", "Excluir campanhas"),
    _perm("comercial", "cupom", "visualizar", "Visualizar cupons"),
    _perm("comercial", "cupom", "criar", "Criar cupons"),
    _perm("comercial", "cupom", "editar", "Editar cupons"),
    _perm("comercial", "cupom", "excluir", "Excluir cupons"),
    _perm("comercial", "fidelidade", "visualizar", "Visualizar fidelidade"),
    _perm("comercial", "fidelidade", "criar", "Criar regras/tiers de fidelidade"),
    _perm("comercial", "fidelidade", "editar", "Editar fidelidade / resgatar pontos"),
    # ---- Fiscal (§10) ----
    _perm("fiscal", "nfse", "visualizar", "Visualizar NFS-e"),
    _perm("fiscal", "nfse", "criar", "Criar / emitir NFS-e"),
    _perm("fiscal", "nfse", "editar", "Editar NFS-e"),
    _perm("fiscal", "nfse", "cancelar", "Cancelar NFS-e"),
    _perm("fiscal", "nfe", "visualizar", "Visualizar NF-e"),
    _perm("fiscal", "nfe", "criar", "Criar / emitir NF-e"),
    _perm("fiscal", "nfe", "editar", "Editar NF-e"),
    _perm("fiscal", "nfe", "cancelar", "Cancelar NF-e"),
    _perm("fiscal", "xml", "visualizar", "Visualizar / exportar XMLs fiscais"),
    _perm("fiscal", "xml", "criar", "Importar XMLs fiscais"),
    _perm("fiscal", "xml", "editar", "Editar XMLs fiscais"),
    _perm("fiscal", "cancelamentos", "visualizar", "Visualizar eventos de cancelamento"),
    _perm("fiscal", "cancelamentos", "criar", "Solicitar eventos de cancelamento"),
    _perm("fiscal", "cancelamentos", "editar", "Parametrizar prazos de cancelamento"),
    _perm("fiscal", "impostos", "visualizar", "Visualizar impostos e apuração"),
    _perm("fiscal", "impostos", "criar", "Criar configurações e alíquotas"),
    _perm("fiscal", "impostos", "editar", "Editar configurações e alíquotas"),
    # ---- Auditoria / Logs ----
    _perm("auditoria", "trilha", "visualizar", "Visualizar trilha de auditoria"),
    _perm("logs", "sistema", "visualizar", "Visualizar logs do sistema"),
    # ---- Relatórios (§11) ----
    _perm("relatorios", "frota", "visualizar", "Visualizar relatórios de frota"),
    _perm("relatorios", "frota", "exportar", "Exportar relatórios de frota"),
    _perm("relatorios", "locacao", "visualizar", "Visualizar relatórios de locação"),
    _perm("relatorios", "locacao", "exportar", "Exportar relatórios de locação"),
    _perm("relatorios", "financeiro", "visualizar", "Visualizar relatórios financeiros"),
    _perm("relatorios", "financeiro", "exportar", "Exportar relatórios financeiros"),
    _perm("relatorios", "fiscal", "visualizar", "Visualizar relatórios fiscais"),
    _perm("relatorios", "fiscal", "exportar", "Exportar relatórios fiscais"),
    _perm("relatorios", "gerencial", "visualizar", "Visualizar relatórios gerenciais"),
    _perm("relatorios", "gerencial", "exportar", "Exportar relatórios gerenciais"),
    _perm("relatorios", "historico", "visualizar", "Visualizar histórico de emissões"),
    _perm("relatorios", "agendamento", "visualizar", "Visualizar agendamentos de relatórios"),
    _perm("relatorios", "agendamento", "criar", "Criar agendamentos de relatórios"),
    _perm("relatorios", "agendamento", "editar", "Editar agendamentos de relatórios"),
    # ---- Motor de PDF (§16) ----
    _perm("documentos", "historico", "visualizar", "Visualizar histórico de documentos PDF"),
    # ---- Integrações (§12) ----
    _perm("integracoes", "pagamentos", "visualizar", "Visualizar integrações de pagamento"),
    _perm("integracoes", "pagamentos", "criar", "Configurar integrações de pagamento"),
    _perm("integracoes", "pagamentos", "editar", "Editar integrações de pagamento"),
    _perm("integracoes", "transito", "visualizar", "Visualizar integração trânsito/DETRAN"),
    _perm("integracoes", "transito", "criar", "Configurar integração trânsito/DETRAN"),
    _perm("integracoes", "transito", "editar", "Editar integração trânsito/DETRAN"),
    _perm("integracoes", "transito", "consultar", "Consultar multas/CNH via trânsito"),
    _perm("integracoes", "credito", "visualizar", "Visualizar integração de crédito"),
    _perm("integracoes", "credito", "criar", "Configurar integração de crédito"),
    _perm("integracoes", "credito", "editar", "Editar integração de crédito"),
    _perm("integracoes", "credito", "consultar", "Consultar score de crédito"),
    _perm("integracoes", "telemetria", "visualizar", "Visualizar integração de telemetria"),
    _perm("integracoes", "telemetria", "criar", "Configurar integração de telemetria"),
    _perm("integracoes", "telemetria", "editar", "Editar integração de telemetria"),
    _perm("integracoes", "telemetria", "sincronizar", "Sincronizar telemetria externa"),
    _perm("integracoes", "api_publica", "visualizar", "Visualizar API Keys públicas"),
    _perm("integracoes", "api_publica", "criar", "Criar API Keys públicas"),
    _perm("integracoes", "api_publica", "editar", "Revogar/editar API Keys públicas"),
    # ---- Automações (§13) ----
    _perm("automacoes", "regras", "visualizar", "Visualizar regras de automação"),
    _perm("automacoes", "regras", "criar", "Criar regras de automação"),
    _perm("automacoes", "regras", "editar", "Editar regras de automação"),
    _perm("automacoes", "regras", "executar", "Executar regras manualmente"),
    _perm("automacoes", "workflows", "visualizar", "Visualizar workflows"),
    _perm("automacoes", "workflows", "criar", "Criar workflows"),
    _perm("automacoes", "workflows", "editar", "Editar workflows"),
    _perm("automacoes", "workflows", "executar", "Aprovar/rejeitar workflows"),
    _perm("automacoes", "agendamentos", "visualizar", "Visualizar jobs Celery Beat"),
    _perm("automacoes", "agendamentos", "executar", "Disparar jobs manualmente"),
    _perm("automacoes", "historico", "visualizar", "Visualizar histórico de automações"),
    # ---- Administração SaaS (super-admin) ----
    _perm("admin", "tenant", "visualizar", "Visualizar empresas (tenants) da plataforma"),
    _perm("admin", "tenant", "criar", "Criar empresas (tenants)"),
    _perm("admin", "tenant", "editar", "Editar empresas (tenants)"),
)

# Índice por código para consultas rápidas.
PERMISSIONS_BY_CODE: dict[str, PermissionDef] = {p.code: p for p in SYSTEM_PERMISSIONS}


# ==========================================================================
# CATÁLOGO DE PAPÉIS-MODELO (semeados por tenant)
# ==========================================================================
ADMIN_EMPRESA = RoleTemplate(
    slug="admin-empresa",
    name="Administrador da Empresa",
    description="Acesso total dentro da própria empresa (tenant).",
    permissions=("*",),
)

GERENTE_FILIAL = RoleTemplate(
    slug="gerente-filial",
    name="Gerente de Filial",
    description="Gestão operacional e relatórios no escopo da(s) filial(is).",
    permissions=(
        "dashboard.painel.visualizar",
        "identidade.usuario.visualizar",
        "configuracoes.empresa.visualizar",
        "configuracoes.filial.visualizar",
        "configuracoes.filial.editar",
        "cadastros.cliente.visualizar",
        "cadastros.cliente.criar",
        "cadastros.cliente.editar",
        "cadastros.cliente.bloquear",
        "cadastros.tabela.visualizar",
        "cadastros.motorista.visualizar",
        "cadastros.motorista.criar",
        "cadastros.motorista.editar",
        "cadastros.parceiro.visualizar",
        "cadastros.parceiro.criar",
        "cadastros.parceiro.editar",
        "cadastros.fornecedor.visualizar",
        "cadastros.fornecedor.criar",
        "cadastros.fornecedor.editar",
        "cadastros.vendedor.visualizar",
        "cadastros.vendedor.criar",
        "cadastros.vendedor.editar",
        "frota.veiculo.visualizar",
        "frota.veiculo.criar",
        "frota.veiculo.editar",
        "frota.veiculo.bloquear",
        "frota.categoria.visualizar",
        "frota.categoria.criar",
        "frota.categoria.editar",
        "frota.marca.visualizar",
        "frota.marca.criar",
        "frota.marca.editar",
        "frota.modelo.visualizar",
        "frota.modelo.criar",
        "frota.modelo.editar",
        "frota.combustivel.visualizar",
        "frota.combustivel.criar",
        "frota.combustivel.editar",
        "frota.acessorio.visualizar",
        "frota.acessorio.criar",
        "frota.acessorio.editar",
        "frota.documentacao.visualizar",
        "frota.documentacao.criar",
        "frota.documentacao.editar",
        "frota.telemetria.visualizar",
        "frota.telemetria.criar",
        "frota.telemetria.editar",
        "manutencao.os.visualizar",
        "manutencao.os.criar",
        "manutencao.os.editar",
        "manutencao.os.aprovar",
        "manutencao.preventiva.visualizar",
        "manutencao.preventiva.criar",
        "manutencao.preventiva.editar",
        "manutencao.corretiva.visualizar",
        "manutencao.corretiva.criar",
        "manutencao.corretiva.editar",
        "manutencao.peca.visualizar",
        "manutencao.peca.criar",
        "manutencao.peca.editar",
        "manutencao.pneu.visualizar",
        "manutencao.pneu.criar",
        "manutencao.pneu.editar",
        "tarifario.tabela.visualizar",
        "tarifario.tabela.criar",
        "tarifario.tabela.editar",
        "tarifario.temporada.visualizar",
        "tarifario.temporada.criar",
        "tarifario.temporada.editar",
        "tarifario.taxa.visualizar",
        "tarifario.taxa.criar",
        "tarifario.taxa.editar",
        "tarifario.protecao.visualizar",
        "tarifario.protecao.criar",
        "tarifario.protecao.editar",
        "tarifario.politica.visualizar",
        "tarifario.politica.criar",
        "tarifario.politica.editar",
        "tarifario.simular.visualizar",
        "reservas.reserva.visualizar",
        "reservas.reserva.criar",
        "reservas.reserva.editar",
        "reservas.reserva.cancelar",
        "reservas.reserva.aprovar",
        "reservas.calendario.visualizar",
        "reservas.disponibilidade.visualizar",
        "reservas.cotacao.visualizar",
        "reservas.cotacao.criar",
        "reservas.cotacao.editar",
        "locacoes.contrato.visualizar",
        "locacoes.contrato.criar",
        "locacoes.contrato.editar",
        "locacoes.contrato.cancelar",
        "locacoes.checkout.visualizar",
        "locacoes.checkout.criar",
        "locacoes.checkout.editar",
        "locacoes.checkin.visualizar",
        "locacoes.checkin.criar",
        "locacoes.checkin.editar",
        "locacoes.renovacao.visualizar",
        "locacoes.renovacao.criar",
        "locacoes.encerramento.visualizar",
        "locacoes.encerramento.reabrir",
        "locacoes.multa.visualizar",
        "locacoes.multa.criar",
        "locacoes.multa.editar",
        "locacoes.avaria.visualizar",
        "locacoes.avaria.criar",
        "locacoes.avaria.editar",
        "financeiro.caixa.visualizar",
        "financeiro.caixa.criar",
        "financeiro.caixa.editar",
        "financeiro.caixa.abrir",
        "financeiro.caixa.fechar",
        "financeiro.receber.visualizar",
        "financeiro.receber.criar",
        "financeiro.receber.editar",
        "financeiro.receber.baixar",
        "financeiro.receber.estornar",
        "financeiro.pagar.visualizar",
        "financeiro.pagar.criar",
        "financeiro.pagar.editar",
        "financeiro.pagar.aprovar",
        "financeiro.pagar.efetivar",
        "financeiro.pix.visualizar",
        "financeiro.pix.criar",
        "financeiro.pix.editar",
        "financeiro.cartoes.visualizar",
        "financeiro.cartoes.criar",
        "financeiro.cartoes.editar",
        "financeiro.bancos.visualizar",
        "financeiro.bancos.criar",
        "financeiro.bancos.editar",
        "financeiro.conciliacao.visualizar",
        "financeiro.conciliacao.criar",
        "financeiro.conciliacao.editar",
        "financeiro.faturamento.visualizar",
        "financeiro.faturamento.criar",
        "financeiro.faturamento.editar",
        "comercial.funil.visualizar",
        "comercial.funil.criar",
        "comercial.funil.editar",
        "comercial.proposta.visualizar",
        "comercial.proposta.criar",
        "comercial.proposta.editar",
        "comercial.proposta.excluir",
        "comercial.campanha.visualizar",
        "comercial.campanha.criar",
        "comercial.campanha.editar",
        "comercial.campanha.excluir",
        "comercial.cupom.visualizar",
        "comercial.cupom.criar",
        "comercial.cupom.editar",
        "comercial.cupom.excluir",
        "comercial.fidelidade.visualizar",
        "comercial.fidelidade.criar",
        "comercial.fidelidade.editar",
        "fiscal.nfse.visualizar",
        "fiscal.nfse.criar",
        "fiscal.nfse.editar",
        "fiscal.nfse.cancelar",
        "fiscal.nfe.visualizar",
        "fiscal.nfe.criar",
        "fiscal.nfe.editar",
        "fiscal.nfe.cancelar",
        "fiscal.xml.visualizar",
        "fiscal.xml.criar",
        "fiscal.xml.editar",
        "fiscal.cancelamentos.visualizar",
        "fiscal.cancelamentos.criar",
        "fiscal.cancelamentos.editar",
        "fiscal.impostos.visualizar",
        "fiscal.impostos.criar",
        "fiscal.impostos.editar",
        "relatorios.frota.visualizar",
        "relatorios.frota.exportar",
        "relatorios.locacao.visualizar",
        "relatorios.locacao.exportar",
        "relatorios.financeiro.visualizar",
        "relatorios.financeiro.exportar",
        "relatorios.fiscal.visualizar",
        "relatorios.fiscal.exportar",
        "relatorios.gerencial.visualizar",
        "relatorios.gerencial.exportar",
        "relatorios.historico.visualizar",
        "documentos.historico.visualizar",
        "relatorios.agendamento.visualizar",
        "relatorios.agendamento.criar",
        "relatorios.agendamento.editar",
        "integracoes.pagamentos.visualizar",
        "integracoes.pagamentos.criar",
        "integracoes.pagamentos.editar",
        "integracoes.transito.visualizar",
        "integracoes.transito.criar",
        "integracoes.transito.editar",
        "integracoes.transito.consultar",
        "integracoes.credito.visualizar",
        "integracoes.credito.criar",
        "integracoes.credito.editar",
        "integracoes.credito.consultar",
        "integracoes.telemetria.visualizar",
        "integracoes.telemetria.criar",
        "integracoes.telemetria.editar",
        "integracoes.telemetria.sincronizar",
        "integracoes.api_publica.visualizar",
        "integracoes.api_publica.criar",
        "integracoes.api_publica.editar",
        "automacoes.regras.visualizar",
        "automacoes.regras.criar",
        "automacoes.regras.editar",
        "automacoes.regras.executar",
        "automacoes.workflows.visualizar",
        "automacoes.workflows.criar",
        "automacoes.workflows.editar",
        "automacoes.workflows.executar",
        "automacoes.agendamentos.visualizar",
        "automacoes.agendamentos.executar",
        "automacoes.historico.visualizar",
        "auditoria.trilha.visualizar",
    ),
)

OPERADOR = RoleTemplate(
    slug="operador",
    name="Operador de Balcão",
    description="Operações do dia a dia (atendimento, reservas, contratos).",
    permissions=(
        "dashboard.painel.visualizar",
        "configuracoes.empresa.visualizar",
        "configuracoes.filial.visualizar",
        "cadastros.cliente.visualizar",
        "cadastros.cliente.criar",
        "cadastros.cliente.editar",
        "cadastros.tabela.visualizar",
        "cadastros.motorista.visualizar",
        "cadastros.motorista.criar",
        "cadastros.motorista.editar",
        "cadastros.parceiro.visualizar",
        "cadastros.vendedor.visualizar",
        "cadastros.vendedor.criar",
        "frota.veiculo.visualizar",
        "frota.categoria.visualizar",
        "frota.marca.visualizar",
        "frota.modelo.visualizar",
        "frota.combustivel.visualizar",
        "frota.acessorio.visualizar",
        "frota.documentacao.visualizar",
        "frota.telemetria.visualizar",
        "manutencao.os.visualizar",
        "manutencao.os.criar",
        "manutencao.preventiva.visualizar",
        "manutencao.corretiva.visualizar",
        "manutencao.corretiva.criar",
        "manutencao.peca.visualizar",
        "manutencao.pneu.visualizar",
        "tarifario.tabela.visualizar",
        "tarifario.taxa.visualizar",
        "tarifario.protecao.visualizar",
        "tarifario.simular.visualizar",
        "reservas.reserva.visualizar",
        "reservas.reserva.criar",
        "reservas.reserva.editar",
        "reservas.reserva.cancelar",
        "reservas.calendario.visualizar",
        "reservas.disponibilidade.visualizar",
        "reservas.cotacao.visualizar",
        "reservas.cotacao.criar",
        "locacoes.contrato.visualizar",
        "locacoes.contrato.criar",
        "locacoes.contrato.editar",
        "locacoes.checkout.visualizar",
        "locacoes.checkout.criar",
        "locacoes.checkout.editar",
        "locacoes.checkin.visualizar",
        "locacoes.checkin.criar",
        "locacoes.checkin.editar",
        "locacoes.renovacao.visualizar",
        "locacoes.renovacao.criar",
        "locacoes.encerramento.visualizar",
        "locacoes.multa.visualizar",
        "locacoes.multa.criar",
        "locacoes.avaria.visualizar",
        "locacoes.avaria.criar",
        "locacoes.avaria.editar",
        "financeiro.caixa.visualizar",
        "financeiro.caixa.criar",
        "financeiro.caixa.editar",
        "financeiro.caixa.abrir",
        "financeiro.caixa.fechar",
        "financeiro.receber.visualizar",
        "financeiro.receber.criar",
        "financeiro.receber.baixar",
        "financeiro.pix.visualizar",
        "financeiro.pix.criar",
        "comercial.funil.visualizar",
        "comercial.funil.criar",
        "comercial.funil.editar",
        "comercial.proposta.visualizar",
        "comercial.proposta.criar",
        "comercial.proposta.editar",
        "comercial.cupom.visualizar",
        "comercial.fidelidade.visualizar",
        "fiscal.nfse.visualizar",
        "fiscal.nfse.criar",
        "fiscal.nfe.visualizar",
        "fiscal.nfe.criar",
        "fiscal.xml.visualizar",
        "fiscal.cancelamentos.visualizar",
        "relatorios.frota.visualizar",
        "relatorios.locacao.visualizar",
        "relatorios.historico.visualizar",
        "documentos.historico.visualizar",
        "integracoes.transito.visualizar",
        "integracoes.credito.consultar",
        "automacoes.historico.visualizar",
    ),
)

AUDITOR = RoleTemplate(
    slug="auditor",
    name="Auditor (Somente Leitura)",
    description="Acesso somente leitura, incluindo trilha de auditoria.",
    permissions=(
        "dashboard.painel.visualizar",
        "identidade.usuario.visualizar",
        "identidade.papel.visualizar",
        "configuracoes.empresa.visualizar",
        "configuracoes.filial.visualizar",
        "cadastros.cliente.visualizar",
        "cadastros.tabela.visualizar",
        "cadastros.motorista.visualizar",
        "cadastros.parceiro.visualizar",
        "cadastros.fornecedor.visualizar",
        "cadastros.vendedor.visualizar",
        "frota.veiculo.visualizar",
        "frota.categoria.visualizar",
        "frota.marca.visualizar",
        "frota.modelo.visualizar",
        "frota.combustivel.visualizar",
        "frota.acessorio.visualizar",
        "frota.documentacao.visualizar",
        "frota.telemetria.visualizar",
        "manutencao.os.visualizar",
        "manutencao.preventiva.visualizar",
        "manutencao.corretiva.visualizar",
        "manutencao.peca.visualizar",
        "manutencao.pneu.visualizar",
        "tarifario.tabela.visualizar",
        "tarifario.temporada.visualizar",
        "tarifario.taxa.visualizar",
        "tarifario.protecao.visualizar",
        "tarifario.politica.visualizar",
        "tarifario.simular.visualizar",
        "reservas.reserva.visualizar",
        "reservas.calendario.visualizar",
        "reservas.disponibilidade.visualizar",
        "reservas.cotacao.visualizar",
        "locacoes.contrato.visualizar",
        "locacoes.checkout.visualizar",
        "locacoes.checkin.visualizar",
        "locacoes.renovacao.visualizar",
        "locacoes.encerramento.visualizar",
        "locacoes.multa.visualizar",
        "locacoes.avaria.visualizar",
        "financeiro.caixa.visualizar",
        "financeiro.receber.visualizar",
        "financeiro.pagar.visualizar",
        "financeiro.pix.visualizar",
        "financeiro.cartoes.visualizar",
        "financeiro.bancos.visualizar",
        "financeiro.conciliacao.visualizar",
        "financeiro.faturamento.visualizar",
        "comercial.funil.visualizar",
        "comercial.proposta.visualizar",
        "comercial.campanha.visualizar",
        "comercial.cupom.visualizar",
        "comercial.fidelidade.visualizar",
        "fiscal.nfse.visualizar",
        "fiscal.nfe.visualizar",
        "fiscal.xml.visualizar",
        "fiscal.cancelamentos.visualizar",
        "fiscal.impostos.visualizar",
        "relatorios.frota.visualizar",
        "relatorios.locacao.visualizar",
        "relatorios.financeiro.visualizar",
        "relatorios.fiscal.visualizar",
        "relatorios.gerencial.visualizar",
        "relatorios.historico.visualizar",
        "documentos.historico.visualizar",
        "relatorios.agendamento.visualizar",
        "integracoes.pagamentos.visualizar",
        "integracoes.transito.visualizar",
        "integracoes.credito.visualizar",
        "integracoes.telemetria.visualizar",
        "integracoes.api_publica.visualizar",
        "automacoes.regras.visualizar",
        "automacoes.workflows.visualizar",
        "automacoes.agendamentos.visualizar",
        "automacoes.historico.visualizar",
        "auditoria.trilha.visualizar",
        "logs.sistema.visualizar",
    ),
)

SYSTEM_ROLE_TEMPLATES: tuple[RoleTemplate, ...] = (
    ADMIN_EMPRESA,
    GERENTE_FILIAL,
    OPERADOR,
    AUDITOR,
)


# ==========================================================================
# LÓGICA PURA DE VERIFICAÇÃO
# ==========================================================================
def expand_permissions(codes: set[str]) -> set[str]:
    """Expande o curinga global ``*`` para todas as permissões do sistema."""
    if "*" in codes:
        return {p.code for p in SYSTEM_PERMISSIONS}
    return codes


def has_permission(
    user_permissions: set[str],
    required: str,
    *,
    is_superuser: bool = False,
) -> bool:
    """Verifica se o conjunto de permissões do usuário satisfaz a exigida.

    Regras:
        * Superusuário tem acesso irrestrito.
        * Curinga global ``*`` concede tudo.
        * Curinga de módulo ``modulo.*`` concede todas as ações do módulo.
        * Caso contrário, exige correspondência exata do código.
    """
    if is_superuser or "*" in user_permissions:
        return True
    if required in user_permissions:
        return True
    module_prefix = required.split(".", 1)[0]
    return f"{module_prefix}.*" in user_permissions
